spring:
  application:
    name: ntech-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://ntech-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
